import { About } from "@/components/About/About";
import { Contact } from "@/components/Contact/Contact";
import { Hero } from "@/components/Hero/Hero";
import { Nav } from "@/components/Menu/Nav";
import { Portfolio } from "@/components/Portfolio/Portfolio";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Superstar - NextJs Tailwind Portfolio Template</title>
        <meta name="description" content="Generated by Superstar" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>
      <main>
        <Nav />
        <Hero />
        <About />
        <Portfolio />
        <Contact />
      </main>
    </div>
  );
}
